### ISSUE TITLE
add refresh option to the jobs page when a job is submitted.

### ISSUE THREAD

**Issue by TOoSmOotH** [sensoroni/sensoroni#2]
Would be nice if you could add a refresh tag to the api so that when forwarded to the jobid page when submitting it auto refreshes once based on the seconds provided. 

`http://hhmaster:9822/securityonion/joblookup?redirectUrl=/sensoroni/&refresh=30&esid=ua74OWsB447sABljG6Po`

**Comment by jertel** [comment]
Closing since this is no longer relevant due to the introduction of real-time push updates.
