### ISSUE TITLE
Color / Text difficult to read

### ISSUE THREAD

**Issue by defensivedepth** [sensoroni/sensoroni#4]
This is somewhat subjective, but I have found that the purple text is a bit difficult to read - whether dark or light theme. The red seems to pop out clearly, but the purple does not.
___

![image](https://user-images.githubusercontent.com/954732/66487979-3e620900-ea7b-11e9-8d52-957e31431db7.png)

**Comment by jertel** [comment]
The latest release has some improvements that might help this issue. Check it out and let me know if there is still difficulties viewing the packet streams.
