### ISSUE TITLE
Feature Request - Ability to set default view

### ISSUE THREAD

**Issue by defensivedepth** [sensoroni/sensoroni#5]
Would be really useful to have the ability to set the default view - specifically: Raw vs. App Level & Hex vs. ASCII

_____

![image](https://user-images.githubusercontent.com/954732/66488329-bd574180-ea7b-11e9-9d94-3d4042538da8.png)

**Comment by jertel** [comment]
This has been on my list of todo's. It will be addressed in the near future.

**Comment by jertel** [comment]
This is now available in the latest version.
